### ISSUE TITLE
better expectation failure messages

### ISSUE THREAD

**Issue by fmobus** [rogeriochaves/elm-test-bdd-style#1]
Given that I have code like

``` elm
 describe "something"
      [ it "gives clear message"
        <| assertEqual 0 20
      , it "does not give clear message"
        <| expect 20 toBe 1
      ]
    ]

```

The first expectation would fail with a helpful message that says `FAILED. Expected: 0; got: 20`, while the second expectation would fail with a rather terse `FAILED. not True`.

Perhaps one way of solving these is giving a little more intelligence to matchers, so that they would hold both the matching function and a failure message building function within them. Something like:

``` elm
type alias Matcher a = { tester: a -> a -> Bool, messager: a -> a -> String }

toBe : Matcher
toBe = { tester   = (==)
       , messager = \actual \expected "expected " ++ expected ++ ", got " ++ actual
```

**Comment by rogeriochaves** [comment]
Having a way to define a custom message for the matchers is a great idea, unfortunately this library works on top of `elm-test`, and `elm-test` doesn't allow to create custom messages for failing tests, because each matcher is a type that is pattern matched by the test runner, as you can see here:

https://github.com/deadfoxygrandpa/elm-test/blob/master/src/ElmTest/Assertion.elm#L14

and here:

https://github.com/deadfoxygrandpa/elm-test/blob/master/src/ElmTest/Run.elm#L46

On the bright side, I managed to use `assertEqual` as default for a better output and still be able to add custom matchers by introducing `toBeThruty`, I opened a PR for thoses changes, what you think?

Pull Request: https://github.com/rogeriochaves/elm-test-bdd-style/pull/2
